### ISSUE TITLE
Reporting Engine always tries to connect with AWS to download resources

### ISSUE THREAD

**Issue by Kartik-Rai** [IHTSDO/reporting-engine#1]
Hi there!,

Whenever we tried to start the reporting-engine-worker, it throws this error 

>  **Error when trying to download the us-to-gb-terms-map.txt file from S3 via :ResourceConfiguration{readonly=true, useCloud=false, local=Local{path='opt/reporting-engine-worker/resources/'}, `cloud=null}**

As we have already turned-off the AWS and cloud settings in the properties file but still it tries to connect with the cloud to download the resources. Also we do not use AWS.
Kindly check and do the needful.

Thanks & Regards
Kartik Rai(NRC India)

**Comment by kaicode** [comment]
Hi @Kartik-Rai,
The resource file is publicly accessible in S3 here:
https://s3.amazonaws.com/validation-resources.ihtsdo/prod/international/us-to-gb-terms-map.txt
Please download it and place in the configured local folder so it can be loaded by the Reporting Engine.
Kind regards,
Kai

**Comment by Kartik-Rai** [comment]
Hi @kaicode ,

Already downloaded the 3 files(acceptable_dose_forms.tsv, cs_words.tsv, us-to-gb-terms-map.txt ) required by the Reporting Engine to the local folder but it still tries to connect with S3, whenever I runs the service.

Thanks & Regards
Kartik Rai(NRC India)

**Comment by kaicode** [comment]
The ResourceDataLoader has an error message which assumes that the resource is coming from S3 but I can see from your resource configuration that you are indeed using the local filesystem.

See https://github.com/IHTSDO/reporting-engine/blob/develop/reporting-engine-worker/src/main/java/org/ihtsdo/termserver/scripting/dao/ResourceDataLoader.java#L80

If you ignore the S3 part of the message, the stack trace should give more detail. Maybe it's a file not found exception or some sort of permissions issue?

**Comment by Kartik-Rai** [comment]
Yes, it's giving an error of "com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.".

As I'm not providing this $(cloud.aws.region.static) in the properties file, and also if I provide a value to this variable, service downloads the 3 empty files(acceptable_dose_forms.tsv, cs_words.tsv, us-to-gb-terms-map.txt ) with the same name. Attaching the 2 logs regarding the same issue.

[Reporting-engine_Error.txt](https://github.com/IHTSDO/reporting-engine/files/4030768/Reporting-engine_Error.txt)

[Reporting-engine_Error2.txt](https://github.com/IHTSDO/reporting-engine/files/4030791/Reporting-engine_Error2.txt)

**Comment by kaicode** [comment]
Could you please try adding the following in your configuration to stop the AWS auto-configuration:
```
spring.autoconfigure.exclude=org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
```

**Comment by Kartik-Rai** [comment]
Still getting the same error(trying to download 3 empty files and hangs there) after adding the above configuration to the properties file, logs are attached.

[Reporting-engine_Error3.txt](https://github.com/IHTSDO/reporting-engine/files/4033881/Reporting-engine_Error3.txt)

**Comment by Kartik-Rai** [comment]
Hi there!,

Tried the every possible solutions but still reporting-engine-worker throws the error of connecting with the AWS S3, and also if I sets the 'cloud.aws.region.static' property with any region(like, us-east-1), still the service tries to download the empty files(acceptable_dose_forms.tsv, cs_words.tsv, us-to-gb-terms-map.txt) and the service hanged up.
Any help will be appreciated.

Regards 
Kartik Rai(NRC India)

**Comment by pgwilliams** [comment]
Hi @Kartik-Rai, I've been assigned this issue and I'm hoping to get some time to look into it tomorrow.
Best Wishes, Peter

**Comment by Kartik-Rai** [comment]
Hi @pgwilliams, 

No issues take your time, just wanted to remind the issue as there was no reply.

Regards 
Kartik Rai(NRC India)

**Comment by Kartik-Rai** [comment]
Hi @pgwilliams, Have you find any solution regarding the issue?

Regards 
Kartik Rai(NRC India)

**Comment by pgwilliams** [comment]
Hi @Kartik-Rai I've coded a fix for this issue and you could either pick it up by checking out the develop branch, or by cherry picking this commit:  https://github.com/IHTSDO/reporting-engine/commit/06bdb2faa455800fd469f45f5f9ec5eb8bbcc826

It tested out fine running on my machine, but your environment may differ.    In the application.properties file you'll want to set both:
archives.useCloud=false
resources.useCloud=false

Good luck!

**Comment by kaicode** [comment]
Let's leave tickets open until the changes get to master please. 
GitHub will actually automatically close it then because this is standard practice.
Thanks for providing the fix Peter.

**Comment by Kartik-Rai** [comment]
Thanks a lot @pgwilliams and also is there any way to access the reporting-engine-worker UI for testing the service.

**Comment by pgwilliams** [comment]
Did you find / get anywhere with the https://github.com/IHTSDO/reporting-ui project?  That's the UI for Reporting.   Actually that interacts directly with https://github.com/IHTSDO/reporting-engine/tree/develop/schedule-manager  which then puts messages on a queue for the reporting-engine-worker to pick up.    There is no further UI for the reporting engine worker itself (themselves, for we spin up as many as we need).    There is a system diagram, I'll see if I can add it into the ReadMe today.

**Comment by Kartik-Rai** [comment]
Yes, there is an UI for https://github.com/IHTSDO/reporting-ui project but there are no different Categories unlike your reporting-ui (https://authoring.ihtsdotools.org/reporting/) that has many different categories (like, ad-hoc queries, drug and substance,etc). So are there any settings in between reporting-ui and schedule manager, as i don't find any settings between them.
Also are there any updates in Readme for the reporting service in future, as there is no clear view of starting the service?

**Comment by pgwilliams** [comment]
The "knowledge" of the various jobs and categories comes from the reporting-engine-worker classes themselves.   Each report class declares what category it belongs to.   The schedule manager is informed about this through the metadata call ("initialise" in the schedule manager API).

You're actually the first party that we are aware of that have tried to get the reporting platform working outside of our own organisation.  As with much of our tooling, we build this for our own requirements and made it available as open source as a "have a go" offering.   But yes, setup instructions are definitely warranted if external users are going to have any hope of recreating our internal setup.   I'll see what we can do about that.

**Comment by pgwilliams** [comment]
Closing as this code has now been merged to master - as discussed above.
